#!/bin/bash
set -euo pipefail

# OS detection for sed -i compatibility
if [ "$(uname)" == "Darwin" ]; then
  SED_INPLACE=(-i '')
else
  SED_INPLACE=(-i)
fi

# Archgate setup: ADR directory symlink + rules.d.ts symlink for TypeScript LSP
mkdir -p .archgate
if [ ! -L .archgate/rules.d.ts ]; then
  [ -e .archgate/rules.d.ts ] && rm -rf .archgate/rules.d.ts
  ln -s ../docs/adrs/rules.d.ts .archgate/rules.d.ts
  echo "Created symlink: .archgate/rules.d.ts -> ../docs/adrs/rules.d.ts"
fi

if [ ! -L .archgate/adrs ]; then
  [ -d .archgate/adrs ] && rm -rf .archgate/adrs
  ln -s ../docs/adrs .archgate/adrs
  echo "Created symlink: .archgate/adrs -> ../docs/adrs"
fi

# Back up .claude/settings.local.json before rm -rf (to prevent loss)
SAVED_SETTINGS_LOCAL=""
if [ -f .claude/settings.local.json ]; then
  SAVED_SETTINGS_LOCAL=$(cat .claude/settings.local.json)
fi

rm -rf .cursor .claude .codex .gemini .cursorignore .geminiignore .mcp.json AGENTS.md CLAUDE.md GEMINI.md

_rulesync() {
  if command -v rulesync >/dev/null 2>&1; then
    rulesync "$@"
  else
    npx rulesync "$@"
  fi
}

_rulesync generate --targets cursor,claudecode,geminicli --features commands,subagents,skills,hooks,mcp,rules,ignore
_rulesync generate --targets codexcli --features rules,skills,mcp,rules

# Deploy .claude/scripts/ (not generated by rulesync, but wiped by the rm -rf above)
echo -e "\nDeploying .claude/scripts/..."
mkdir -p .claude/scripts
cp .rulesync/scripts/*.sh .claude/scripts/
chmod +x .claude/scripts/*.sh

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

# Merge additional settings into .claude/settings.json
echo -e "\nMerging extra settings into .claude/settings.json..."
if [ -f .rulesync/configs/.claude-settings.json ] && [ -f .claude/settings.json ]; then
  # $t * $g: rulesync output ($g) wins for scalar conflicts.
  # Permission arrays are explicitly concatenated and deduplicated so both sources contribute.
  jq -s '
    .[0] as $t | .[1] as $g |
    ($t * $g)
    | .permissions.allow = ((($t.permissions.allow // []) + ($g.permissions.allow // [])) | unique)
    | .permissions.deny  = ((($t.permissions.deny  // []) + ($g.permissions.deny  // [])) | unique)
  ' .rulesync/configs/.claude-settings.json .claude/settings.json > "$TMP"
  mv "$TMP" .claude/settings.json
fi

# Merge .mcp.json>mcpServers into .claude/settings.json
echo -e "\nMerging mcpServers from .mcp.json into .claude/settings.json..."
if [ -f .mcp.json ] && [ -f .claude/settings.json ]; then
  jq -s '.[0] * { mcpServers: .[1].mcpServers }' .claude/settings.json .mcp.json > "$TMP"
  mv "$TMP" .claude/settings.json
fi

# Restore and merge .claude/settings.local.json
echo -e "\nMerging .claude/settings.local.json..."
if [ -n "$SAVED_SETTINGS_LOCAL" ]; then
  echo "$SAVED_SETTINGS_LOCAL" | jq -s '.[0] * .[1]' .rulesync/configs/.claude-settings.local.json - > "$TMP"
  mv "$TMP" .claude/settings.local.json
else
  cp .rulesync/configs/.claude-settings.local.json .claude/settings.local.json
fi

# Fix prompt format in .gemini/commands/*.toml files
echo -e "\nFixing prompt format in .gemini/commands/*.toml files...\n"
for f in .gemini/commands/*.toml; do
  [ -f "$f" ] || continue
  sed "${SED_INPLACE[@]}" "s/prompt = \"\"\"/prompt = '''/g" "$f"
  sed "${SED_INPLACE[@]}" "s/^\"\"\"$/'''/g" "$f"
done

echo -e "\nAll post-generation steps completed successfully.\n"
